### ISSUE TITLE
Changing skeleton slightly

### ISSUE THREAD

**Issue by cpopell** [getgrav/grav-skeleton-hpstr-site#4]
If I want to change your 'posts' page to 'archive', and your 'blog' folder to 'posts', what do I need to do? I got the archive working by changing the folder name, the markdown file name, and the twig file name--but what do I need to change to make the homepage work again once I change things?

**Comment by flaviocopes** [comment]
You need to change the page title and page slug / folder name.

Markdown and Twig do not need to be changed, otherwise you'll also need to change the theme, which then puts you in the situation of having to create a child theme, as editing a theme is not ideal since you'll lose the ability to apply updates.

**Comment by cpopell** [comment]
What's the actual folder for the homepage? That's the only thing not
working.

**Comment by flaviocopes** [comment]
It depends. The home page is a page set in your System configuration (user/config/system.yaml) as "home.alias", or via the Admin plugin "Home page"
